### ISSUE TITLE
🔥🦑 Migrate to Fire Squid

### ISSUE THREAD

**Issue by vikiival** [kodadot/click#22]
[Migrate to Fire Squid](https://docs.subsquid.io/docs/guides/migrate-to-fire-squid/)

Spotify mood song: 

[Scooter - Fire](https://open.spotify.com/track/6dWoVPmEFhPXSaqNxwea1I?si=41301309a43a489b)

**Comment by yangwao** [comment]
waiting from SQ to resolve some EVM bug 👀

**Comment by vikiival** [comment]
@eldargab any ETA?

**Comment by yangwao** [comment]
https://twitter.com/subsquid/status/1564322148466020352 👀
